language: r
warnings_are_errors: true
sudo: false
cache: packages

before_install: echo "options(repos = c(CRAN='http://cran.r-project.org'))" > ~/.Rprofile

os:
  - linux
  - osx

env:
 global:
   - CRAN: http://cran.rstudio.com
 matrix:
   - RVERSION=oldrel
   - RVERSION=release
   - RVERSION=devel

notifications:
  email:
    on_success: change
    on_failure: change


