language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

os:
  - linux
  - osx

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change


