language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

before_install: echo "options(repos = c(CRAN='http://cran.r-project.org'))" > ~/.Rprofile

os:
  - linux
  - osx

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change


