language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

r_github_packages:
  - hadley/devtools
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change


