# Sample .travis.yml for R projects

language: c
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx

env:
 global:
   - CRAN: http://cran.rstudio.com


notifications:
  email:
    on_success: change
    on_failure: change
