language: r
sudo: false
cache: packages

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

r_github_packages:
  - hadley/devtools
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change


